# Tcl script generated by PlanAhead

set reloadAllCoreGenRepositories false

set tclUtilsPath "/home/gonza/Xilinx/14.7/ISE_DS/PlanAhead/scripts/pa_cg_utils.tcl"

set repoPaths ""

set cgIndexMapPath "/home/gonza/Maestria/FPGA_Comms/OFDM_TP/OFDM_TP.srcs/sources_1/ip/cg_lin_index_map.xml"

set cgProjectPath "/home/gonza/Maestria/FPGA_Comms/OFDM_TP/OFDM_TP.srcs/sources_1/ip/fifo_generator_v9_3_0/coregen.cgc"

set ipFile "/home/gonza/Maestria/FPGA_Comms/OFDM_TP/OFDM_TP.srcs/sources_1/ip/fifo_generator_v9_3_0/fifo_16_8a1.xco"

set ipName "fifo_16_8a1"

set chains "CUSTOMIZE_CURRENT_CHAIN INSTANTIATION_TEMPLATES_CHAIN"

set bomFilePath "/home/gonza/Maestria/FPGA_Comms/OFDM_TP/OFDM_TP.srcs/sources_1/ip/fifo_generator_v9_3_0/pa_cg_bom.xml"

set cgPartSpec "xc3s500e-4fg320"

set hdlType "VHDL"

# generate the IP
set result [source "/home/gonza/Xilinx/14.7/ISE_DS/PlanAhead/scripts/pa_cg_reconfig_core.tcl"]

exit $result

